### ISSUE TITLE
Break the fork?

### ISSUE THREAD

**Issue by conorhastings** [socialtables/react-color#4]
- [ ] sir-hex-alot
- [ ] react-rainbow
- [x] rothko
- [ ] pollock
- [ ] react-couleur
- [ ] kinemacolor
- [ ] technicolor
- [x] dreamcoat
- [ ] agfacolor
- [ ] anthotype
- [ ] autochrome
- [ ] chromogenic
- [ ] ektachrome
- [ ] dufaycolor
- [ ] dye-destruction
- [ ] cibachrome
- [ ] ilfochrome
- [ ] dye-transfer
- [ ] kodachrome
- [ ] heliochrome
- [ ] lippmann
- [x] react-spectrum
- [ ] react-picker
- [ ] reactachrome

**Comment by mcwhittemore** [comment]
What would we call it?

**Comment by rickyvetter** [comment]
sir-hex-alot

**Comment by rickyvetter** [comment]
react-rainbow

**Comment by rickyvetter** [comment]
rothko

**Comment by rickyvetter** [comment]
pollock

**Comment by mcwhittemore** [comment]
react-couleur

**Comment by mcwhittemore** [comment]
Kinemacolor

**Comment by mcwhittemore** [comment]
Technicolor

**Comment by ecgeiser** [comment]
dreamcoat

**Comment by rickyvetter** [comment]
Any of these: https://en.wikipedia.org/wiki/List_of_photographic_processes
Agfacolor
Anthotype
Autochrome Lumière, 1903
Carbon print, 1862
Chromogenic positive (Ektachrome)
E-3 process
E-4 process
E-6 process
Chromogenic negative
C-41 process
RA-4 process
Dufaycolor
Dye destruction
Cibachrome
Ilfochrome
Dye-transfer process
Kodachrome
K-12 process
K-14 process
Heliochrome
Lippmann plate, 1891

**Comment by conorhastings** [comment]
react-spectrum
react-picker

**Comment by mcwhittemore** [comment]
reactachrome
